default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - deploy

build_react:
  stage: build
  script: |
    echo "Building React app..."
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t yotan9508/fakedetection-react:$CI_COMMIT_SHA .
    docker push yotan9508/fakedetection-react:$CI_COMMIT_SHA
    docker build -t yotan9508/fakedetection-react:latest .
    docker push yotan9508/fakedetection-react:latest

deploy_react:
  stage: deploy
  script: |
    echo "Deploying React app..."
    docker pull yotan9508/fakedetection-react:$CI_COMMIT_SHA
    docker stop react-container || true
    docker rm react-container || true
    docker run -d -p 3000:80 --name react-container yotan9508/fakedetection-react:$CI_COMMIT_SHA
  tags:
    - react-ec2-runner
  only:
    - main
