default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - deploy

build_react:
  stage: build
  script: |
    echo "Building React app..."
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t yotan9508/fakedetection-react:$CI_COMMIT_SHA .
    docker push yotan9508/fakedetection-react:$CI_COMMIT_SHA

deploy_react:
  stage: deploy
  script: |
    echo "Triggering deployment on EC2..."
    curl -X POST "http://${EC2_PUBLIC_IP}:5000/deploy-react"
  only:
    - main
